document: modularity-testing
version: 1
name: haproxy
modulemd-url: https://raw.githubusercontent.com/container-images/haproxy/master/haproxy.yaml
service:
    port: 80
packages:
    rpms:
        - haproxy
testdependecies:
    rpms:
        - nc
module:
    docker:
        start: "docker run -it -p 8077:80 -v $(pwd)/local-haproxy.cfg:/etc/haproxy/haproxy.cfg:Z"
        labels:
            description: "HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments."
            io.k8s.description: "HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high availability environments."
        source: https://github.com/container-images/haproxy
        container: docker.io/modularitycontainers/haproxy
    rpm:
        start: systemctl start haproxy
        stop: systemctl stop haproxy
        status: systemctl status haproxy
        repos:
            - http://mirror.vutbr.cz/fedora/releases/25/Everything/x86_64/os/
            - https://phracek.fedorapeople.org/haproxy-module-repo/
    test:
        processrunning:
            - 'ls  /proc/*/exe -alh | grep haproxy'


