document: modularity-testing
version: 1
name: memcached
source: https://github.com/container-images/memcached.git
modulemd-url: https://src.fedoraproject.org/cgit/modules/memcached.git/plain/memcached.yaml
service:
    port: 11211
packages:
    rpms:
        - bash
testdependecies:
    rpms:
        - nc
default_module: docker
module:
    docker:
        setup: echo Do magic with general config stored on host;
               echo More magic
        cleanup: echo Cleanup magic
        start: "docker run -it -e CACHE_SIZE=128 -p 11211:11211"
        labels:
            description: "memcached is a high-performance, distributed memory"
            io.k8s.description: "memcached is a high-performance, distributed memory"
        container: docker.io/phracek/memcached
    rpm:
        setup: echo Do magic with general config stored on host;
               echo More magic
        cleanup: echo Cleanup magic
        start: /bin/true
        stop: /bin/true
        status: /bin/true
        repo: https://kojipkgs.fedoraproject.org/repos/module-481d2dd61f4ae110/latest/x86_64/


