document: modularity-testing
version: 1
name: bash
modulemd-url: https://src.fedoraproject.org/cgit/modules/memcached.git/plain/memcached.yaml
packages:
    rpms:
        - bash
        - microdnf
        - rpm
module:
    docker:
        container: docker.io/phracek/memcached
    rpm:
        repo: https://kojipkgs.fedoraproject.org/repos/module-481d2dd61f4ae110/latest/x86_64/

