document: modularity-testing
version: 1
name: bash
modulemd-url: https://src.fedoraproject.org/cgit/modules/memcached.git/plain/memcached.yaml
module:
    docker:
        container: docker.io/phracek/memcached
    rpm:
        repo: https://phracek.fedorapeople.org/memcached-module-repo/

