document: modularity-testing
version: 1
name: bash
modulemd-url: http://raw.githubusercontent.com/container-images/memcached/master/memcached.yaml
module:
    docker:
        container: docker.io/phracek/memcached
    rpm:
        repo: https://phracek.fedorapeople.org/memcached-module-repo/

